using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entities.Enumerations.Tables
{
    public enum Tables
    {
        Customers_Billings,
        Customers_Customer,
        Customers_Group,
        Customers_Groups_CustomerGroup,
        Customers_Shippings,
        Items_Brand,
        Items_Category,
        Items_Discounts_ApplyToItem,
        Items_Discounts_Condition_BuyXgetY,
        Items_Discounts_Condition_Combo,
        Items_Discounts_Condition_FixedAmount,
        Items_Discounts_Condition_Percentage,
        Items_Discounts_Discount,
        Items_Fees_Services_Service,
        Items_Fees_Shippings_Shipping,
        Items_Fees_Surcharges_Surcharge,
        Items_Fees_Taxes_Tax,
        Items_Groups_Group,
        Items_Groups_GroupItem,
        Items_Menus_Menu,
        Items_Menus_MenuItem,
        Items_Products_Bundle,
        Items_Products_Modifiers_Modifier,
        Items_Products_Modifiers_ModifierItem,
        Items_Products_PriceOverride_ProductPriceOverride,
        Items_Products_PriceOverride_ProductVariantPriceOverride,
        Items_Products_Product,
        Items_Products_Units_Unit,
        Loyalties,
        Orders_Order,
        Orders_Detail,
        Payments_Apis,
        Payments_Cashdrawers_Cashdrawer,
        Payments_Cashdrawers_Detail,
        Payments_Cashs_Cash,
        Payments_Cashs_Detail,
        Payments_Vouchers,
        Payments_Payment,
        Points_Devices_Device,
        Points_Devices_Settings,
        Points_Locations_Location,
        Points_Locations_DiningOption,
        Points_Locations_Working,
        Points_Locations_Receipt,
        Pos_Floors_Floor,
        Pos_Sections_Section,
        Pos_Tables_FloorTable,
        Pos_Tables_Table,
        Reports,
        Settings,
        Systems,
        Users_Companies_Company,
        Users_Companies_Legals,
        Users_Companies_Permissions,
        Users_Staffs_Staff,
    }
}
